# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_auto_20170522_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='position',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
