# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_auto_20170522_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='position',
            field=models.ForeignKey( default=1 ,on_delete=django.db.models.deletion.CASCADE, to='instructors.Position'),
            preserve_default=False,
        ),
    ]
