# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_auto_20170522_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='course',
            field=models.ManyToManyField(to='instructors.Course'),
        ),
    ]
